Fix IndexOutOfBoundsException in PersistentDispatcherMultipleConsumers
This error is due to the resolution of a conflict while committing bfa30dd49d09

java.lang.IndexOutOfBoundsException: toIndex = 76
2021-10-28T17:06:02,977 [bookkeeper-ml-workers-OrderedExecutor-5-0] WARN  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [omg/post-book-resp-event-consumer/persistent/post-book-response-event-REPLAY][post-book-response-event-consumer-replay] Error while replaying entries
org.apache.bookkeeper.mledger.ManagedLedgerException: Other exception
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 76
Oct 28 13:06:02 ocdataeng06 0cc94feb3fc7: 2021-10-28T17:06:02,979 [main-EventThread] INFO  org.apache.bookkeeper.meta.ZkLedgerUnderreplicationManager - Latch countdown due to ZK event: WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/ledgers/underreplication/ledgers/0000/0000