[fix][bookie] Correctly handle list configuration values (#17661)
* [fix][bookie] Correctly handle list configuration values

* Remove unused import

### Motivation

When the `metadataServiceUri` or the `zkServers` configuration for `BookieRackAffinityMapping` is provided as a comma delimited list, it is automatically parsed into an ArrayList by the configuration class because the Bookkeeper configuration class relies on the defaults in the `org.apache.commons.configuration.AbstractConfiguration` class. Here is a sample error:

```
2022-07-29T19:25:43,437+0000 [main] ERROR org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to initialize DNS Resolver org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping, used default subnet resolver
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
```

Also, see #6349 and https://github.com/apache/pulsar/issues/6343 for context.

### Modifications

* Move the `castToString` method out to a shared class.
* Use the `castToString` method to safely get the configuration value.

### Verifying this change

This PR includes a test.

### Documentation

- [x] `doc-not-needed`

(cherry picked from commit 69deb1f6e440578234c142bf4a962bc2c7ace5e5)
(cherry picked from commit 97598159c56d40a9527d2b16c0ccab1be732c9b4)